# Generated by Django 3.0.6 on 2020-05-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200518_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
